--import Coxeter.Auxi
--import Coxeter.Basic
--import Coxeter.Hecke
--import Coxeter.BruhatOrder
import Coxeter.CoxeterMatrix.Basic
import Coxeter.AlternatingWord
import Coxeter.BruhatOrder
import Coxeter.StrongExchange
--import Coxeter.Hecke2
--import Coxeter.Length_reduced_word
